spring.application.name=iesi-back
spring.datasource.url=jdbc:postgresql://localhost:5432/iesi_db
spring.datasource.username=postgres
spring.datasource.password=mudinamico
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8080
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alumnos@iesijujuy.edu.ar
spring.mail.password=rrjpfjzdrocbbmjk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
app.upload.dir=D:/files/
