spring.application.name=iesi-back
spring.datasource.url=jdbc:postgresql://147.93.35.109:5432/iesi_db
spring.datasource.username=postgres
spring.datasource.password==KIDvsKAT07
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alumnos@iesijujuy.edu.ar
spring.mail.password=rrjpfjzdrocbbmjk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true