spring.application.name=iesi-back
spring.datasource.url=jdbc:postgresql://147.93.35.109:5432/iesi_revision
spring.datasource.username=postgres
spring.datasource.password==KIDvsKAT07
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
server.port=8443
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:keystores/keystore.p12
server.ssl.key-store-password=mudinamico
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alumnos@iesijujuy.edu.ar
spring.mail.password=rrjpfjzdrocbbmjk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
app.upload.dir=/var/www/app/files/
spring.jackson.time-zone=America/Argentina/Buenos_Aires
mercadopago.access-token=APP_USR-6329408864377734-080500-9ae4e42618460e78fcc01cbe3e5e04ee-2607956408