spring.application.name=iesi-back
spring.datasource.url=jdbc:postgresql://localhost:5432/iesi_db
spring.datasource.username=postgres
spring.datasource.password=mudinamico
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
server.port=8080
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alumnos@iesijujuy.edu.ar
spring.mail.password=rrjpfjzdrocbbmjk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
app.upload.dir=D:/files/
spring.jackson.time-zone=America/Argentina/Buenos_Aires
mercadopago.point.terminal-id=TU_TERMINAL_ID
mercadopago.access-token=APP_USR-8662130267783644-062521-d9443d73e33c606c9b07e7d52d375b83-2607956408
#mercadopago.qr.external-pos-id=iesicajatramites
mercadopago.qr.external-pos-id=iesicajaestatica

